admin:
    path:     /
    defaults: { _controller: "AcmeDemoBundle:User:adminIndex" }

admin_home:
    path:     /index
    defaults: { _controller: "AcmeDemoBundle:User:adminIndex" }

admin_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeDemoBundle:User:show" }

admin_new:
    path:     /new
    defaults: { _controller: "AcmeDemoBundle:User:new" }

admin_create:
    path:     /create
    defaults: { _controller: "AcmeDemoBundle:User:create" }
    requirements: { _method: post }

admin_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeDemoBundle:User:edit" }

admin_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeDemoBundle:User:update" }
    requirements: { _method: post|put }

admin_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeDemoBundle:User:directDelete" }
    requirements: { _method: get|delete }

admin_table:
    path:     /table
    defaults: { _controller: "AcmeDemoBundle:User:showTable" }

admin_gallery:
    path:     /gallery
    defaults: { _controller: "AcmeDemoBundle:User:showGallery" }
    
admin_manageGallery:
    path:     /{id}/managegallery
    defaults: { _controller: "AcmeDemoBundle:User:manageGallery" }
    